### ISSUE TITLE
App not shipped with NC17 and no longer available in store

### ISSUE THREAD

**Issue by Schmuuu** [nextcloud/files_texteditor#185] opened 2019-10-12 17:26 UTC
Hello,

This app is no longer available in the nextcloud app store. The following link leads to an empty page:
https://apps.nextcloud.com/apps/files_texteditor

I think this could be the reason, why this app gets removed during the update of Nextcloud server to version 17.

I originally discovered this issue, when I tried to open markdown files in the plain text editor, but didn't have the option available anymore. Disabling the new app "Text" had the effect, that I could only download .md and .txt files, but they didn't open anymore. 
I couldn't find this app in my app section (neither enabled nor disabled) and not on the filesystem. 

I tried two things without success:
- search the app in the app store (to download and enable it again)
- restore the app from the backup created during NC17 update (no way to update the app then)

Could you please make this app available in the NC store again, please?
I believe many users find this app extremely important; especially because the new "Text" app has a few flaws which make it unusable for a few users.

Thanks a lot.

**Edit:** Not sure, who is really maintaining the app. Could you have a look here please @juliushaertl , you made one of the last changes :)

**Comment by juliushaertl** [comment] 2019-10-23 14:23
Not sure about doing another release since we will mainly focus development on the text app now. cc @rullzer 

The app should still work fine for 17 (restored from your backup) if you adjust the max-version in appinfo/info.xml

**Comment by rullzer** [comment] 2019-10-28 13:01
No it won't be shipped. We could just dump it in the appstore.
I'll try to find some time to do that this week.

**Comment by Schmuuu** [comment] 2019-10-28 13:12
Oh nooo 😢 
This app is so great. Simple and great. In combination with files_markdown it works absolutely flawless.
Unfortunately the new Text app doesn't work that flawless, but has issues with fomatting changes and data loss. 
Please don't remove this app until Text can be used in production without worries.

**Comment by BrookeDot** [comment] 2019-11-07 19:02
> We could just dump it in the appstore. I'll try to find some time to do that this week.

Thanks @rullzer having it in the appstore will be a big help. There is also an issue open over on the `files_markdown` app regarding the missing `files_texteditor` causing breakage in the markdown app (https://github.com/icewind1991/files_markdown/issues/135 ). I think if that app is updated to work with the new Text app then the original app may not be needed. However, for now both Text apps appear to be necessary. 

Thanks again for your work!

**Comment by wardwouts** [comment] 2019-11-12 15:58
I'll always have a need for an editor that does not do rendering for me. Or at least lets me turn it off. If that could be a configuration option in the new Text app, it would be fine. Until that time, I prefer the old editor.

**Comment by E1k3** [comment] 2019-12-01 17:25
This really needs to be maintained in the future as the new WYSIWYG "Text" app does not support the preview extension apps that were possible with this editor. I and many others greatly prefer the raw+preview style of editing.

**Comment by Vince4Git** [comment] 2020-01-02 09:33
For me, the issue is not in the "view style".
I do not understand the decision to change the Nextcloud text editor with something different which is no more a text editor and which does not respect the data of the user in the file.

Now:

1. it is no more possible to edit text file (.txt) from Nextcloud without mardown !!
2. Nextcloud text editor reformat the content of the file of the user !!

It should be possible to disable Nextcloud text editor which is no more neutral on the file content.
It should be possible to install better markdown applications in Nextcloud.

This is the first time that I'm so disappointed by Nextcloud.
Please could you restore Markdown Editor and the Simple text editor (please stop to mix everything).

Best Regards,
Vincent.

**Comment by ManuelFte** [comment] 2020-01-12 18:36
Agreed with everything @Vince4Git said, plus I'd also like to note that this new app doesn't have code syntax highlighting. So in summary, we previously had:

- Plain text editor.
- Code editor.
- Markdown editor.

While we now have:

- No plain text editor.
- No code editor.
- Half-baked markdown editor.

This is more a downgrade than an upgrade, and I don't think the new app should have been shipped in this state to be used in production while deprecating the other two. I'm reverting to the previous apps that were more mature until the new app becomes an actual alternative that can be used in the same scenarios.

Please don't replace apps with alternatives with less functionalities that only work for a smaller range of use cases.

**Comment by odo2063** [comment] 2020-02-01 13:28
It is getting worse...the min-version changed to 19....now does somebody know to get it to work in NC17...just downloading and changing the min-version does not work? or how do i make NC recognize files for this app(it is activatable)

**Comment by Code1110** [comment] 2020-02-05 01:02
I had success making it work with NC17 by following these steps:
1. `git clone https://github.com/nextcloud/files_texteditor.git`
2. `git checkout ea69f31b4ffdc8254d14deeb7a5c830cc4ae2e44`
3. align `min-version` in `info.xml` to 17
4. copy the whole folder to `/var/www/html/apps/files_texteditor`

If you are using nextcloud in docker, you have to copy the folder using `docker cp` and then go inside the container and recursively change the owner of the folder to `www-data`. A lot of pain to make it work again after a simple version upgrade.

**Comment by develroo** [comment] 2020-02-06 02:15
This appears to be broken again for 18. Even following the above steps and putting max-version to 18 still no joy. Even if you disable the text app the file will try and download instead of opening in the markdown viewer. Seems whatever meta tag needs to be set to open the markdown in another app is not being honoured and they are forcing people to use the text app by default, which I think we can all agree is fine as a text app but useless as a markdown editor.

**Comment by odo2063** [comment] 2020-02-06 10:13
> I had success making it work with NC17 by following these steps:
> 
>     1. `git clone https://github.com/nextcloud/files_texteditor.git`
> 
>     2. `git checkout ea69f31b4ffdc8254d14deeb7a5c830cc4ae2e44`
> 
>     3. align `min-version` in `info.xml` to 17
> 
>     4. copy the whole folder to `/var/www/html/apps/files_texteditor`
> 
> 
> If you are using nextcloud in docker, you have to copy the folder using `docker cp` and then go inside the container and recursively change the owner of the folder to `www-data`. A lot of pain to make it work again after a simple version upgrade.

I have this so far...i can activate it. But it will start when i click on a .txt file.

**Comment by odo2063** [comment] 2020-02-06 10:15
> This appears to be broken again for 18. Even following the above steps and putting max-version to 18 still no joy. Even if you disable the text app the file will try and download instead of opening in the markdown viewer. Seems whatever meta tag needs to be set to open the markdown in another app is not being honoured and they are forcing people to use the text app by default, which I think we can all agree is fine as a text app but useless as a markdown editor.

We(in terms of me and my colleagues) don't need markdown! We need a simple Texteditor with codehighlighting.

**Comment by kevinclevenger** [comment] 2020-02-11 23:15
> This appears to be broken again for 18. Even following the above steps and putting max-version to 18 still no joy. Even if you disable the text app the file will try and download instead of opening in the markdown viewer. Seems whatever meta tag needs to be set to open the markdown in another app is not being honoured and they are forcing people to use the text app by default, which I think we can all agree is fine as a text app but useless as a markdown editor.

Followed the steps and still the same here. For me this issue blocks files_markdown. The default editor app is incomplete and unusable, so I guess for now shell in and edit with vim (which is contrary to the purpose of a facility like Nextcloud).

**Comment by Greek64** [comment] 2020-02-16 11:08
@odo2063  @kevinclevenger 
This app is still tagged according to each nextcloud version (and each tag has the correct info.xml), so I would suggest to checkout the tags instead.

I can confirm it working on nextcloud 18.0.1.

Small tutorial (assuming Nextcloud version v17.0.3):
```
# Go To App Folder
cd <PATH-TO-NEXTCLOUD>/custom-apps

# Clone Repo if not already done
git clone https://github.com/nextcloud/files_texteditor.git

# Checkout respective version
cd files_texteditor
git fetch
git checkout v17.0.3

# Repair ownership (Here assuming www-data is the Nextcloud user. Change accordingly)
cd ..
chown -R www-data:www-data files_texteditor

#DONE. Now enable in Admin Area
```

Also do note that the app will not automatically start (if you have the `Text` App enabled). You have to start it by pressing on the 3 dots and clicking on `Edit in plain text editor`

**Comment by develroo** [comment] 2020-02-16 19:35
Ok so i did all that pulled the git checked it out to 18.01 , set the correct perms, and restarted all the containers. Bit still not seeing the edit as text in the 3 dots. 

I am using the nextcloud [docker compose example.](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/postgres/fpm)

I am not seeing any errors in the logs either and the markdown editor is installed and enabled. 
 

Any idea how to debug this then ?

**Comment by Greek64** [comment] 2020-02-16 19:58
Hmm, odd.
What does the Admin Area `Apps` Section say about the `Plain Text Editor` (NOT the `Text` App)?
Which version? Is it enabled?

**Comment by develroo** [comment] 2020-02-16 22:02
Yes 

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - analytics: 2.0.0
  - announcementcenter: 3.7.0
  - apporder: 0.9.0
  - breezedark: 18.0.6
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.8
  - dashboard: 6.0.0
  - dashboardcharts: 0.1.3
  - dav: 1.14.0
  - deck: 0.8.0
  - encryption: 2.6.0
  - external: 3.5.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_external: 1.9.0
  - files_fulltextsearch_tesseract: 1.4.0
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_texteditor: 2.10.0
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - fulltextsearch_elasticsearch: 1.5.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.2
  - nextbackup: 19.12.1
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - richdocuments: 3.5.2
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.4
  - support: 1.1.0
  - survey_client: 1.6.0
  - suspicious_login: 3.1.0
  - systemtags: 1.8.0
  - theming: 1.9.0
  - theming_customcss: 1.5.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_gateway: 0.15.1
  - twofactor_totp: 4.1.2
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflow_pdf_converter: 1.3.1
  - workflow_script: 1.3.1
  - workflowengine: 2.0.0
Disabled:
  - files_automatedtagging
  - terms_of_service
  - text
  - twofactor_admin
  - user_ldap

```

**Comment by Greek64** [comment] 2020-02-16 22:21
OK, the fact that you are not seeing the `Edit in plain text editor` option is simply because you have `Text` disabled. You should be able to open text by clicking normally on the documents.

Other that that I reached the end of my usefulness.
I can provide you with my enabled app list that you can use to compare, maybe an enabled app of yours is interfering in some way...
<details>
<summary>App List</summary>
<pre>
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - announcementcenter: 3.7.0
  - apporder: 0.9.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - checksum: 0.4.4
  - cloud_federation_api: 1.1.0
  - cms_pico: 1.0.5
  - comments: 1.8.0
  - dav: 1.14.0
  - deck: 0.8.0
  - drawio: 0.9.4
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_downloadactivity: 1.7.0
  - files_external: 1.9.0
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.7.0
  - files_retention: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_texteditor: 2.10.0
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.1
  - impersonate: 1.5.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - metadata: 0.11.1
  - nextcloud_announcements: 1.7.0
  - notes: 3.1.5
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - polls: 1.3.0
  - previewgenerator: 2.2.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - files_snapshots
  - recommendations
  - sharerenamer
  - user_ldap
</pre>
</details>

**Comment by develroo** [comment] 2020-02-16 22:29
Uh oh celebrated too soon.. :( It opens the editor but the edit text is blank ?

![Screenshot from 2020-02-16 22-26-12](https://user-images.githubusercontent.com/7777993/74613995-bd430e80-510b-11ea-9b2a-dbbfe4912dd1.png)
![Screenshot from 2020-02-16 22-26-29](https://user-images.githubusercontent.com/7777993/74613999-c338ef80-510b-11ea-85e9-c0d0e93bfbb7.png)
![Screenshot from 2020-02-16 22-26-42](https://user-images.githubusercontent.com/7777993/74614005-c8963a00-510b-11ea-8e33-106e3d512e5a.png)

**Comment by Greek64** [comment] 2020-02-16 22:33
Can confirm the behavior.
This happens when you have a `Readme.md` in the directory.
Delete it, and create another file and try to edit that. It should work.

I suggest opening a new github issue for that.

**Comment by develroo** [comment] 2020-02-16 22:37
Yeah.. seems it was just the readme that was affected. Some sort of weird caching issue because you can edit it with the new editor and the changes stick but in the text editor the changes don't appear. 

Anyway for now it seems to work so I'll keep my fingers crossed and hope it stays that way. 

Thanks.

**Comment by pieter-groeneweg** [comment] 2020-02-19 15:03
> 
> 
> Oh nooo 😢
> This app is so great. Simple and great. In combination with files_markdown it works absolutely flawless.
> Unfortunately the new Text app doesn't work that flawless, but has issues with fomatting changes and data loss.
> Please don't remove this app until Text can be used in production without worries.

Totally agree....

I don't need a markdown editor.. I need a plain text editor... 
with the plain editor I could change code in (html, js, css, php even with some highlighting) in folders mounted to Nextcloud.

Since there is nothing that can replace it (yet) it should not be dropped.

**Comment by rogercreagh** [comment] 2020-03-12 11:32
Yes confirm that if Text is enabled then opening a .txt files with "Open in Text editor" presents a blank screen if there is a Readme.md in the same folder.
Is this a bug in Texteditor, or Text? Where to report it? 
It is a pain because the facility to have a small readme text presented at the top of the fles list for each folder is really usefull (although the implementation is buggy in its display and inline editing options)
I can also confirm that if you turn off Text's use of the workspace area between the breadcrumbs and the files list with 
`occ config:app:set text workspace_available --value=0`
Presence of a Readme.md file doesn't cause any problem (and it is not displayed) and it all works as expected, click on .txt or .md file opens in Text, dots menu "Open in plain text editor" opens with texteditor.
What needs fixing is the bug in Files or Text that is causing problems with the Readme being there.

**Comment by Greek64** [comment] 2020-03-12 12:33
@rogercreagh 
I would say this is a `files_texteditor` (Plain Text Editor) Bug, since the "Readme" functionality (called Workspaces) is "embedded" in Nextcloud 18, and all Apps ought to support it.

**Comment by rogercreagh** [comment] 2020-03-12 12:45
@Greek64 yep, that makes sense. Thanks for the pointer to Workspaces; still learning my way around. Seems possible that it is Text that is causing the problem though since disabling Text's use of workspace removes the issue. Can't see how opening a non readme.md text file would fail if it was purely a files_texteditor bug.

**Comment by Greek64** [comment] 2020-03-12 14:25
@rogercreagh 
You are right.
How about opening an issue on both, link them, and let the devs figure out, where the bug resides.

**Comment by rogercreagh** [comment] 2020-03-12 18:37
Update - the problem is that there is an id clash between the div used for the richtext workspace for Text displaying readme and the overlay used by texteditor.
Both use `<div ide="editor" ....` so when the overlay loads the text file it pokes it into the workspace editor space.
This was actually fixed in js/editor.js three months ago according to github - the div is now `id="filestexteditor" but this change is not picked up in the 18.0.2 release for some reason, although it is in the head.
Unfortunately `git checkout master` which does get the right files then requires a `make` to build them and that fails on my system with an error:
`make: *** No rule to make target `.babelrc', needed by `build/editor.js'.  Stop.`
Can someone build a working version for download please?

**Comment by e-alfred** [comment] 2020-03-30 21:42
@rogercreagh I think the only real way to fix this is to release the app to the App Store? @rullzer It would be awesome if you could make a release there.

**Comment by joshmorel** [comment] 2020-04-01 14:15
It seems [IE11 is still used by some people](https://help.nextcloud.com/t/issue-with-text-app-under-internet-explorer-11/76035) (but also listed as [supported by NC](https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#web-browser) and the new Text app doesn't work (lack of Proxy polyfill?). Another reason to add to App Store (at least for now).

**Comment by pabsta** [comment] 2020-04-21 03:39
It is sad that the markdown editor is out of Nextcloud. Is there anyone who is actively working on a replacement for the text app? I would like to contribute.

**Comment by tanghus** [comment] 2020-04-21 08:12
@pabsta MarkDown editor is still there: https://apps.nextcloud.com/apps/files_markdown
`files_texteditor` is missing, though.

I'm on NC 18 and for some reason the "old" `files_texteditor` with both `min-version` and `max-version` is set to 17, but it works just fine. I had the Text app disabled and clicking and clicking on a `.php` or `.md` file opened in `files_texteditor`and `files_markdown` respectively.
To test I enabled Text but soon after disabled it again. I'm sure it has great potential as a collaborative editor, but for daily use it's just not usable.

Good thing is that PRs seem to get accepted so if the nextclouders would test and package the app the community could probaly maintain the app? cc @icewind1991 @Schmuuu @schiessle

**Comment by tanghus** [comment] 2020-04-21 08:20
Guess I'm trying to kick in an open door ;) https://github.com/icewind1991/files_markdown/issues/136#issuecomment-614696605

**Comment by e-alfred** [comment] 2020-04-21 12:03
The app works well on Nextcloud 18 and is only a release to the App Store away from general availability. :-)

**Comment by juliushaertl** [comment] 2020-04-22 08:00
Finally pushed the release to the app store https://apps.nextcloud.com/apps/files_texteditor

**Closed by juliushaertl** 2020-04-22 08:00 UTC

**Comment by Merrit** [comment] 2020-10-01 19:15
> I can confirm it working on nextcloud 18.0.1.
> 
> Small tutorial (assuming Nextcloud version v17.0.3):
> 
> ```
> # Go To App Folder
> cd <PATH-TO-NEXTCLOUD>/custom-apps
> 
> # Clone Repo if not already done
> git clone https://github.com/nextcloud/files_texteditor.git
> 
> # Checkout respective version
> cd files_texteditor
> git fetch
> git checkout v17.0.3
> 
> # Repair ownership (Here assuming www-data is the Nextcloud user. Change accordingly)
> cd ..
> chown -R www-data:www-data files_texteditor
> 
> #DONE. Now enable in Admin Area
> ```
> 
> Also do note that the app will not automatically start (if you have the `Text` App enabled). You have to start it by pressing on the 3 dots and clicking on `Edit in plain text editor`

New to Nextcloud, this is not working for me at all. I downloaded the latest release of Plain text editor..

Nextcloud: 19.0.3
Plain text editor: 2.11.0
Markdown Editor: 2.3.1

I have tried enabling / disabling the Text / Plain text editor / Markdown Editor in various configurations, results are either:

1. Opens in default Text
2. Downloads file

The 3-dot menu has no entry for opening in other..

![image](https://user-images.githubusercontent.com/9575627/94853074-d37eb000-03f8-11eb-8259-007a83299fc5.png)
