### ISSUE TITLE
Certificate "4356" has been revoked 

### ISSUE THREAD

**Issue by Kobberholm** [nextcloud/files_texteditor#271] opened 2020-08-31 12:49 UTC
When I try to install the Plain text editor app, I get an error message `Certificate "4356" has been revoked `and the app will not install.
It seems to be related to https://github.com/nextcloud/server/issues/20674

**Downloading the app from https://github.com/nextcloud/files_texteditor, moving it into the apps dir and `occ app:enable files_texteditor` installs the app without issues.**

### Steps to reproduce
1. Install the docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm compose file from:
https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm
2.
   a: Find Plain text editor in the Apps section and click install
   b: Alternatively run command `occ app:install files_texteditor`

### Expected behaviour
Plain text editor app should install

### Actual behaviour
Instead of installing, I get the error message `Certificate "4356" has been revoked `

### Server configuration
**Operating system**:
Ubuntu 20.04

**Web server:**
Nginx 1.19.2 (current nginx:alpine docker image)

**Database:**
MariaDB 10.5.5 (default MariaDB docker image)

**PHP version:**
PHP 7.4.9 (php:7.4-fpm-alpine3.12 docker image)

**Nextcloud version:**
19.0.2 (current nextcloud:fpm-alpine docker image)

**Where did you install Nextcloud from:**
Docker Hub

**List of activated apps:**
All apps are the ones from the recommended install.
  - accessibility: 1.5.0
  - activity: 2.12.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.1
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - richdocuments: 3.7.3
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.3
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0

**Nextcloud configuration:**

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "not.my.actual.domain"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.2.2",
        "overwrite.cli.url": "http:\/\/not.my.actual.domain",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.12.0",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "30"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "2.0.4",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "3.3.0",
            "types": ""
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "dav"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1598875128.7044",
            "lastcron": "1598875501",
            "lastupdatedat": "1598875128.7065",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "theming.variables": "b92d206521717ac032f8aa58d3c7ff2f",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.16.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.8.0",
            "types": "logging"
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.4.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "1.4.1",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.9.1",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "0.7.0",
            "types": ""
        },
        "richdocuments": {
            "enabled": "yes",
            "installed_version": "3.7.3",
            "types": "filesystem,dav,prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "yes",
            "has_reference_id": "yes",
            "installed_version": "9.0.3",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "prevent_group_restriction"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.2.1",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "logging"
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.0.1",
            "types": "dav"
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.1.0",
            "types": "filesystem"
        }
    }
}
```

### Client configuration
**Browser:**
Firefox 78.0.2

**Operating system:**
Kubuntu 19.10

#### Nextcloud log (data/nextcloud.log)
```

{"reqId":"ENns9jy1OZ5t1uGcDSET","level":2,"time":"2020-08-31T11:58:41+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","version":""}
{"reqId":"ENns9jy1OZ5t1uGcDSET","level":2,"time":"2020-08-31T11:58:41+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","version":""}
{"reqId":"ENns9jy1OZ5t1uGcDSET","level":3,"time":"2020-08-31T11:58:41+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"--","app":"jsresourceloader","method":"GET","url":"/","message":"Could not find resource js/setup.js to load","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","version":""}
{"reqId":"SnJWweqKzjcXPovdzNtF","level":2,"time":"2020-08-31T11:58:44+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","version":""}
{"reqId":"SnJWweqKzjcXPovdzNtF","level":2,"time":"2020-08-31T11:58:44+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","version":""}
{"reqId":"Qdf8hrHQ8wI5SyAvqVfm","level":3,"time":"2020-08-31T12:00:33+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"shoutout","app":"settings","method":"POST","url":"/settings/apps/enable","message":{"Exception":"Exception","Message":"Certificate \"4356\" has been revoked","Code":0,"Trace":[{"file":"/var/www/html/apps/settings/lib/Controller/AppSettingsController.php","line":444,"function":"downloadApp","class":"OC\\Installer","type":"->","args":["files_texteditor"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->","args":[["files_texteditor"],[]]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AppSettingsController","enableApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.AppSettings.enableApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/html/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/html/lib/base.php","line":1012,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/enable"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Installer.php","Line":239,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","version":"19.0.2.2"}
```

**Comment by son0203** [comment] 2020-09-02 19:15
Same issue here!

**Comment by muranava** [comment] 2020-09-04 18:20
same problem

**Comment by laodzu** [comment] 2020-09-08 08:23
Also same problem.

**Comment by fds2610** [comment] 2020-09-10 08:39
same problem here.

**Comment by MorrisJobke** [comment] 2020-09-10 09:27
This was revoked in end of April - https://github.com/nextcloud/app-certificate-requests/pull/282#issuecomment-620403222

@juliushaertl Mind to upload a new version with a proper signature?

**Comment by LukaPitamic** [comment] 2020-09-17 13:54
any progress on solving this issue?

**Comment by torbennehmer** [comment] 2020-09-19 16:18
Same problem here

**Comment by Dani-Pi** [comment] 2020-09-20 18:28
Same error message here on NextCloudPi. I'm not able to install plain from nextcloud app store. And the new rich text editor is no good alternative when working with markdown files within the cloud...

**Comment by rschulzUK** [comment] 2020-09-23 12:26
Probably the same issue on Hetzner Storage Share (Nextcloud 19.0.3 - 19.0.3.1). The error message when the installation fails lacks specifics.

**Comment by juliushaertl** [comment] 2020-09-23 12:45
I'm currently preparing a new release with the updated certificate, once that is uploaded installing should work fine again as mentioned in https://github.com/nextcloud/files_texteditor/issues/271#issuecomment-690110446

**Comment by LukaPitamic** [comment] 2020-09-23 12:50
@juliushaertl WTG! thank you for your time!

**Comment by son0203** [comment] 2020-09-23 13:07
@juliushaertl Great news! Thank you Julius!

**Comment by VitharMe** [comment] 2020-09-25 15:57
@juliushaertl Thanks man!

**Comment by SnailDove** [comment] 2020-09-26 08:06
> I'm currently preparing a new release with the updated certificate, once that is uploaded installing should work fine again as mentioned in [#271 (comment)](https://github.com/nextcloud/files_texteditor/issues/271#issuecomment-690110446)

Thx for your efforts!

**Comment by stratosgear** [comment] 2020-10-04 17:47
I still have issues installing this! Registering!

**Comment by HiFiJ** [comment] 2020-10-05 19:44
Affected as well, subscribing. Thanks for your efforts!

**Comment by HiFiJ** [comment] 2020-10-06 09:37
Hi,

btw. the given workaround 
`Downloading the app from https://github.com/nextcloud/files_texteditor, moving it into the apps dir and occ app:enable files_texteditor installs the app without issues.`

is not working for me; I get 

`-chrootsh-4.2$ php73 occ app:enable files_texteditor
The current PHP memory limit is below the recommended value of 512MB.
Certificate "4356" has been revoked
`

**Comment by juliushaertl** [comment] 2020-10-08 15:24
Release is at https://github.com/nextcloud/files_texteditor/releases/tag/v2.12.0

However the app store currently has issues and requests are timing out. I'll upload the release once it is working again.

**Comment by juliushaertl** [comment] 2020-10-09 05:47
Pushed out as 2.13.0 to the app store, one more version bump to correct a mismatch between the github release and the appinfo.xml.

**Closed by juliushaertl** 2020-10-09 05:47 UTC
Labels: 1. to develop, bug, high

**Comment by fds2610** [comment] 2020-10-09 07:46
2.14.0 installed from app store, but no files can be edited.

**Comment by Merrit** [comment] 2020-10-10 14:26
Confirm this seems to be working as expected for me now (using context menu for open allows me to edit in Markdown Editor).

Thanks much! :tada:

**Comment by dgedgedge** [comment] 2020-10-18 08:37
Hi,
It seems that it happens also on the "Reader (ebook reader)" application.

Steps to reproduce : 
Go to application management, try to install "Reader (ebook reader)" V1.4.2.

`## Server configuration detail

**Operating system:** Linux 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.3.23

**PHP version:** 7.3.19-1~deb10u1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, msgpack, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, memcached, Zend OPcache

**Nextcloud version:** 19.0.4 - 19.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.1
 - admin_audit: 1.9.0
 - analytics: 2.5.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.0.4
 - carnet: 0.22.3
 - checksum: 0.4.5
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contacts: 3.4.0
 - contactsinteraction: 1.0.0
 - cookbook: 0.7.6
 - dav: 1.15.0
 - deck: 1.1.2
 - documentserver_community: 0.1.8
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_external: 1.10.0
 - files_markdown: 2.3.1
 - files_mindmap: 0.0.23
 - files_pdfviewer: 1.8.0
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - geoblocker: 0.3.2
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - maps: 0.1.6
 - music: 0.16.0
 - nextcloud_announcements: 1.8.0
 - notes: 3.6.4
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - onlyoffice: 6.0.2
 - password_policy: 1.9.1
 - photos: 1.1.0
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - recommendations: 0.7.0
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - spreed: 9.0.4
 - support: 1.2.1
 - survey_client: 1.7.0
 - systemtags: 1.9.0
 - tasks: 0.13.4
 - text: 3.0.1
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - updatenotification: 1.9.0
 - viewer: 1.3.0
 - workflowengine: 2.1.0
Disabled:
 - audioplayer
 - audioplayer_editor
 - encryption
 - groupfolders
 - keeweb
 - user_ldap
 - user_usage_report

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "owncloud.fager.fr",
        "192.168.0.110",
        "89.156.37.141"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/owncloud.fager.fr",
    "dbtype": "mysql",
    "version": "19.0.4.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 0,
    "logtimezone": "Europe\/Paris",
    "logfile": "\/var\/log\/nextcloud.log",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "updater.release.channel": "stable",
    "mail_smtpauth": 1,
    "mail_sendmailmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "trashbin_retention_obligation": "auto, 100",
    "has_rebuilt_cache": true,
    "app_install_overwrite": [
        "files_reader"
    ]
}
```
</details>

**External storages:** yes

<details><summary>External storage configuration</summary>

```
No mounts configured
```
</details>

**Encryption:** no

**User-backends:** 
 * OC\User\Database


**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:81.0) Gecko/20100101 Firefox/81.0

`
