### ISSUE TITLE
Search box not displaying on key commands

### ISSUE THREAD

**Issue by mcleanholmes** [nextcloud/files_texteditor#76] opened 2017-12-10 23:45 UTC
### Steps to reproduce
1. Open any file applicable to the Texteditor 
2. Use the keyboard shortcut Command-F or Ctrl-F

### Expected behaviour
The find/ search box menu should appear

### Actual behaviour
Error occurs in the console saying the /index.php/apps/files/ext-searchbox.js because non script MIME types are not allowed wen 'X-Content-Type: no sniff' is given.

### Server configuration

**Operating system**: 
macOS Sierra 10.12.6
Server 5.3.1

**Web server:**
Apache2

**Database:**
10.1.24-MariaDB - Homebrew

**PHP version:**
5.6.30

**Nextcloud version:** (see Nextcloud admin page)
12.0.4

**Where did you install Nextcloud from:**
nextcloud.com

**List of activated apps:**

Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - admin_notifications: 1.0.1
  - announcementcenter: 3.1.1
  - apporder: 0.4.1
  - audioplayer: 2.2.1
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.7
  - checksum: 0.3.5
  - circles: 0.13.6
  - comments: 1.2.0
  - contacts: 2.0.1
  - dashboard: 4.0.5
  - dav: 1.3.0
  - drawio: 0.8.8
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_automatedtagging: 1.2.2
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.2
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ojsxc: 3.3.2
  - previewgenerator: 1.0.7
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.1
  - rainloop: 5.0.6
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - theming_customcss: 1.0.0
  - twofactor_backupcodes: 1.1.1
  - unsplash: 1.0.5
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
  - workin2gether: 0.9.6
Disabled:
  - activitylog
  - defaultgroup
  - direct_menu
  - encryption
  - firstrunwizard
  - password_policy
  - templateeditor
  - user_external

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "ocz44zrckg1n",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "dev.endlesss.cloud",
            "beta.endlesss.cloud"
        ],
        "datadirectory": "\/Volumes\/My-Book-Pro\/Users",
        "overwrite.cli.url": "https:\/\/dev.endlesss.cloud",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "endlesss-cloud_dev",
        "dbhost": "server.endlesss.co",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "America\/Chicago",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "cloud",
        "mail_smtpmode": "php",
        "mail_domain": "dev.endlesss.cloud",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.endlesss.co",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "maintenance": false,
        "loglevel": 0,
        "theme": "",
        "debug": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.5.2",
            "types": "filesystem"
        },
        "activitylog": {
            "enabled": "no",
            "installed_version": "0.0.1",
            "types": ""
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "admin_notifications": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "logging"
        },
        "announcementcenter": {
            "enabled": "yes",
            "installed_version": "3.1.1",
            "types": "logging"
        },
        "apporder": {
            "enabled": "yes",
            "installed_version": "0.4.1",
            "ocsid": "174715",
            "order": "[\"\/index.php\/apps\/files\/\",\"\/index.php\/apps\/gallery\/\",\"\/index.php\/apps\/notes\/\",\"\/index.php\/apps\/audioplayer\/\",\"\/index.php\/apps\/rainloop\/\",\"\/index.php\/apps\/activity\/\",\"\/index.php\/apps\/external\/1\",\"\/index.php\/apps\/external\/2\",\"\/index.php\/apps\/announcementcenter\/\",\"\/index.php\/apps\/circles\/\",\"\/index.php\/apps\/dashboard\/\"]",
            "types": ""
        },
        "audioplayer": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "26"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.0.2",
            "types": ""
        },
        "calendar": {
            "enabled": "[\"admin\",\"computerscience\",\"webteam\",\"family\",\"photography\",\"dev131\"]",
            "installed_version": "1.5.7",
            "types": ""
        },
        "checksum": {
            "enabled": "yes",
            "installed_version": "0.3.5",
            "types": "filesystem"
        },
        "circles": {
            "allow_federated": "0",
            "allow_linked_groups": "1",
            "enabled": "yes",
            "installed_version": "0.13.6",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "[\"admin\",\"computerscience\",\"webteam\",\"family\",\"photography\",\"dev131\"]",
            "installed_version": "2.0.1",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "ajax",
            "installed.bundles": "[\"CoreBundle\",\"CoreBundle\"]",
            "installedat": "1485043848.1843",
            "lastcron": "1512949167",
            "lastupdateResult": "[]",
            "lastupdatedat": "1512949160",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "{\"core\":{\"INVALID_HASH\":{\".htaccess\":{\"expected\":\"da8e0075f23227b107fc705aa1b20378107d3a1c195d96ed13e5f4f25c38d6c660aab75be183ae5799a4ff7eae0ea739a14c944430ee8bb9e9a824235aa136eb\",\"current\":\"fe5df73dc3f0b4af210bb23b69b594ad431942da9ad261c3bace5dbdb758720cf2c9093f0d1c8c49da22a8f40d81c03e5c464ab20cb211e7e0c4b15d4f1570d3\"}}}}",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "repairlegacystoragesdone": "yes",
            "scss.variables": "d3478778099568952ac38928437df7aa",
            "umgmt_show_email": "true",
            "umgmt_show_last_login": "true",
            "updater.secret.created": "1512851911",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "[\"admin\",\"computerscience\",\"webteam\",\"family\",\"photography\",\"dev131\"]",
            "installed_version": "4.0.5",
            "types": ""
        },
        "dav": {
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "defaultgroup": {
            "enabled": "no",
            "installed_version": "0.3.0",
            "types": "prevent_group_restriction"
        },
        "direct_menu": {
            "enabled": "no",
            "installed_version": "0.10.2",
            "ocsid": "169148",
            "types": ""
        },
        "drawio": {
            "DrawioLang": "auto",
            "DrawioTheme": "kennedy",
            "DrawioUrl": "https:\/\/www.draw.io",
            "DrawioXml": "yes",
            "enabled": "yes",
            "installed_version": "0.8.8",
            "types": "filesystem"
        },
        "external": {
            "enabled": "yes",
            "installed_version": "2.0.3",
            "max_site": "2",
            "sites": "{\"1\":{\"icon\":\"external.png\",\"lang\":\"\",\"type\":\"link\",\"device\":\"\",\"id\":1,\"name\":\"Password Change\",\"url\":\"https:\\\/\\\/server.endlesss.co\\\/changepassword\"}}",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.7.2",
            "types": "filesystem"
        },
        "files_accesscontrol": {
            "enabled": "yes",
            "installed_version": "1.2.5",
            "types": "filesystem"
        },
        "files_automatedtagging": {
            "enabled": "yes",
            "installed_version": "1.2.2",
            "types": "filesystem"
        },
        "files_downloadactivity": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        },
        "files_external": {
            "allow_user_mounting": "yes",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "ftp,dav,owncloud,sftp,amazons3,dropbox,googledrive,swift,\\OC\\Files\\Storage\\SFTP_Key"
        },
        "files_markdown": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": ""
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_retention": {
            "enabled": "yes",
            "installed_version": "1.1.2",
            "types": "filesystem"
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "2.1",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "17.0.0",
            "types": ""
        },
        "groupfolders": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "logreader": {
            "enabled": "[\"admin\"]",
            "installed_version": "2.0.0",
            "levels": "01111",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.1",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "[\"admin\",\"computerscience\",\"webteam\",\"family\",\"photography\",\"dev131\"]",
            "installed_version": "2.3.2",
            "ocsid": "174554",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.0.5",
            "types": "authentication"
        },
        "ojsxc": {
            "apiSecret": "dJY1SZ6u6wjTM5pRT7euHmF",
            "boshUrl": "",
            "chromeExtension": "",
            "enabled": "yes",
            "externalServices": "",
            "firefoxExtension": "",
            "iceCredential": "",
            "iceSecret": "",
            "iceTtl": "",
            "iceUrl": "",
            "iceUsername": "",
            "installed_version": "3.3.2",
            "ocsid": "162257",
            "serverType": "internal",
            "timeLimitedToken": "false",
            "types": "prelogin",
            "xmppDomain": "",
            "xmppOverwrite": "false",
            "xmppPreferMail": "false",
            "xmppResource": "",
            "xmppStartMinimized": "true"
        },
        "onlyoffice": {
            "enabled": "no",
            "installed_version": "1.1.3",
            "ocsid": "174798",
            "skey": "1496236299300",
            "types": "filesystem"
        },
        "orcid": {
            "enabled": "no",
            "installed_version": "0.9.1",
            "types": ""
        },
        "password_policy": {
            "enabled": "no",
            "installed_version": "1.2.2",
            "types": ""
        },
        "previewgenerator": {
            "enabled": "yes",
            "installed_version": "1.0.7",
            "lastActivity": "1512746104",
            "types": "filesystem"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction"
        },
        "quota_warning": {
            "alert_email": "yes",
            "enabled": "yes",
            "info_email": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem",
            "warning_email": "yes"
        },
        "rainloop": {
            "enabled": "[\"admin\",\"computerscience\",\"webteam\",\"dev131\",\"photography\",\"family\"]",
            "installed_version": "5.0.6",
            "ocsid": "165254",
            "rainloop-autologin": "1",
            "types": ""
        },
        "richdocuments": {
            "enabled": "no",
            "installed_version": "1.12.34",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "[\"admin\"]",
            "installed_version": "1.2.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "no",
            "installed_version": "2.0.2",
            "types": "prevent_group_restriction"
        },
        "survey_client": {
            "enabled": "[\"admin\"]",
            "installed_version": "1.0.0",
            "last_report": "{\"id\":\"ocz44zrckg1n\",\"items\":[[\"server\",\"version\",\"12.0.3.3\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"none\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"cron\"],[\"php\",\"version\",\"5.6.30\"],[\"php\",\"memory_limit\",134217728],[\"php\",\"max_execution_time\",0],[\"php\",\"upload_max_filesize\",10737418240],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"10.1.24\"],[\"database\",\"size\",15860383744],[\"apps\",\"activity\",\"2.5.2\"],[\"apps\",\"activitylog\",\"disabled\"],[\"apps\",\"admin_audit\",\"1.2.0\"],[\"apps\",\"admin_notifications\",\"1.0.0\"],[\"apps\",\"announcementcenter\",\"3.1.0\"],[\"apps\",\"apporder\",\"0.4.0\"],[\"apps\",\"audioplayer\",\"2.2.0\"],[\"apps\",\"bruteforcesettings\",\"disabled\"],[\"apps\",\"calendar\",\"1.5.6\"],[\"apps\",\"checksum\",\"0.3.5\"],[\"apps\",\"circles\",\"0.13.6\"],[\"apps\",\"comments\",\"1.2.0\"],[\"apps\",\"contacts\",\"2.0.1\"],[\"apps\",\"dashboard\",\"4.0.5\"],[\"apps\",\"dav\",\"1.3.0\"],[\"apps\",\"defaultgroup\",\"disabled\"],[\"apps\",\"direct_menu\",\"disabled\"],[\"apps\",\"drawio\",\"0.8.8\"],[\"apps\",\"external\",\"2.0.3\"],[\"apps\",\"federatedfilesharing\",\"1.2.0\"],[\"apps\",\"federation\",\"1.2.0\"],[\"apps\",\"files\",\"1.7.2\"],[\"apps\",\"files_accesscontrol\",\"1.2.5\"],[\"apps\",\"files_automatedtagging\",\"1.2.2\"],[\"apps\",\"files_downloadactivity\",\"1.1.1\"],[\"apps\",\"files_external\",\"1.3.0\"],[\"apps\",\"files_markdown\",\"2.0.1\"],[\"apps\",\"files_pdfviewer\",\"1.1.1\"],[\"apps\",\"files_retention\",\"1.1.2\"],[\"apps\",\"files_sharing\",\"1.4.0\"],[\"apps\",\"files_texteditor\",\"2.4.1\"],[\"apps\",\"files_trashbin\",\"1.2.0\"],[\"apps\",\"files_versions\",\"1.5.0\"],[\"apps\",\"files_videoplayer\",\"1.1.0\"],[\"apps\",\"firstrunwizard\",\"disabled\"],[\"apps\",\"gallery\",\"17.0.0\"],[\"apps\",\"groupfolders\",\"1.1.0\"],[\"apps\",\"logreader\",\"2.0.0\"],[\"apps\",\"lookup_server_connector\",\"1.0.0\"],[\"apps\",\"nextcloud_announcements\",\"1.1\"],[\"apps\",\"notes\",\"2.3.1\"],[\"apps\",\"notifications\",\"2.0.0\"],[\"apps\",\"oauth2\",\"1.0.5\"],[\"apps\",\"ojsxc\",\"3.3.1\"],[\"apps\",\"onlyoffice\",\"disabled\"],[\"apps\",\"orcid\",\"disabled\"],[\"apps\",\"password_policy\",\"disabled\"],[\"apps\",\"previewgenerator\",\"1.0.7\"],[\"apps\",\"provisioning_api\",\"1.2.0\"],[\"apps\",\"quota_warning\",\"1.1.1\"],[\"apps\",\"rainloop\",\"5.0.3\"],[\"apps\",\"richdocuments\",\"disabled\"],[\"apps\",\"serverinfo\",\"1.2.0\"],[\"apps\",\"sharebymail\",\"1.2.0\"],[\"apps\",\"spreed\",\"disabled\"],[\"apps\",\"survey_client\",\"1.0.0\"],[\"apps\",\"systemtags\",\"1.2.0\"],[\"apps\",\"tasks\",\"0.9.5\"],[\"apps\",\"templateeditor\",\"disabled\"],[\"apps\",\"theming\",\"1.3.0\"],[\"apps\",\"theming_customcss\",\"1.0.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.1.1\"],[\"apps\",\"unsplash\",\"1.0.5\"],[\"apps\",\"updatenotification\",\"1.2.0\"],[\"apps\",\"user_ldap\",\"1.2.1\"],[\"apps\",\"user_saml\",\"1.3.2\"],[\"apps\",\"workflowengine\",\"1.2.0\"],[\"apps\",\"workin2gether\",\"0.9.6\"],[\"apps\",\"zenodo\",\"disabled\"],[\"stats\",\"num_files\",15043059],[\"stats\",\"num_users\",18],[\"stats\",\"num_storages\",162],[\"stats\",\"num_storages_local\",18],[\"stats\",\"num_storages_home\",72],[\"stats\",\"num_storages_other\",72],[\"stats\",\"num_comments\",1],[\"stats\",\"num_comment_markers\",1],[\"stats\",\"num_systemtags\",2],[\"stats\",\"num_systemtags_mappings\",13],[\"files_sharing\",\"num_shares\",83],[\"files_sharing\",\"num_shares_user\",25],[\"files_sharing\",\"num_shares_groups\",3],[\"files_sharing\",\"num_shares_link\",5],[\"files_sharing\",\"num_shares_link_no_password\",5],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_3_1\",\"3\"],[\"files_sharing\",\"permissions_4_1\",\"44\"],[\"files_sharing\",\"permissions_3_4\",\"1\"],[\"files_sharing\",\"permissions_0_5\",\"1\"],[\"files_sharing\",\"permissions_3_15\",\"1\"],[\"files_sharing\",\"permissions_4_15\",\"3\"],[\"files_sharing\",\"permissions_0_17\",\"9\"],[\"files_sharing\",\"permissions_0_19\",\"2\"],[\"files_sharing\",\"permissions_0_21\",\"2\"],[\"files_sharing\",\"permissions_0_31\",\"11\"],[\"files_sharing\",\"permissions_1_31\",\"3\"],[\"files_sharing\",\"permissions_2_31\",\"3\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1511242209",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "[\"admin\",\"computerscience\",\"webteam\",\"family\",\"photography\",\"dev131\"]",
            "installed_version": "0.9.5",
            "types": ""
        },
        "templateeditor": {
            "enabled": "no",
            "installed_version": "0.2",
            "types": ""
        },
        "theming": {
            "cachebuster": "47",
            "color": "#4483C7",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "name": "Endlesss Cloud",
            "slogan": "Web Design and Development",
            "types": "logging",
            "url": "https:\/\/endlesss.cloud"
        },
        "theming_customcss": {
            "cachebuster": "1512355801891",
            "customcss": "#body-login input.primary {\nbackground-color: rgba(255, 255, 255, .5) !important;\nborder: 1px solid rgba(240,240,240,.9);\n}\n#header .logo,#header .logo-icon {\n background-image:url(\/\/endlesss.cloud\/core\/img\/logo.svg?v=36)\n}",
            "enabled": "[\"admin\"]",
            "installed_version": "1.0.0",
            "types": ""
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "unsplash": {
            "enabled": "yes",
            "installed_version": "1.0.5",
            "types": "authentication"
        },
        "updatenotification": {
            "admin_notifications": "1.0.1",
            "announcementcenter": "3.1.1",
            "apporder": "0.4.1",
            "audioplayer": "2.2.1",
            "calendar": "1.5.6",
            "checksum": "0.3.5",
            "circles": "0.13.6",
            "contacts": "2.0.1",
            "core": "12.0.4.3",
            "defaultgroup": "0.3.0",
            "direct_menu": "0.10.2",
            "enabled": "[\"admin\"]",
            "files_accesscontrol": "1.2.5",
            "files_markdown": "2.0.1",
            "installed_version": "1.2.0",
            "notes": "2.3.2",
            "ojsxc": "3.3.2",
            "previewgenerator": "1.0.7",
            "quota_warning": "1.1.1",
            "rainloop": "5.0.6",
            "richdocuments": "1.11.34",
            "types": "",
            "update_check_errors": "0"
        },
        "user_ldap": {
            "enabled": "yes",
            "has_memberof_filter_support": "",
            "home_folder_naming_rule": "",
            "installed_version": "1.2.1",
            "last_jpegPhoto_lookup": "0",
            "ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "ldap_attributes_for_group_search": "",
            "ldap_attributes_for_user_search": "",
            "ldap_backup_host": "",
            "ldap_backup_port": "",
            "ldap_base": "dc=server,dc=endlesss,dc=co",
            "ldap_base_groups": "dc=server,dc=endlesss,dc=co",
            "ldap_base_users": "dc=server,dc=endlesss,dc=co",
            "ldap_cache_ttl": "600",
            "ldap_configuration_active": "1",
            "ldap_default_ppolicy_dn": "",
            "ldap_display_name": "cn",
            "ldap_dn": "",
            "ldap_dynamic_group_member_url": "",
            "ldap_email_attr": "mail",
            "ldap_experienced_admin": "0",
            "ldap_expert_username_attr": "uid",
            "ldap_expert_uuid_group_attr": "",
            "ldap_expert_uuid_user_attr": "",
            "ldap_gid_number": "gidNumber",
            "ldap_group_display_name": "cn",
            "ldap_group_filter": "(&(|(objectclass=apple-group)(objectclass=posixGroup))(|(cn=computerscience)(cn=computerscienceadmin)(cn=csc215)(cn=dev131)(cn=family)(cn=leeandheatherwedding)(cn=photography)(cn=staff)(cn=viewfindereditors)(cn=viewfinderweb)(cn=webteam)(cn=workgroup)))",
            "ldap_group_filter_mode": "0",
            "ldap_group_member_assoc_attribute": "memberUid",
            "ldap_groupfilter_groups": "computerscience\ncomputerscienceadmin\ncsc215\ndev131\nfamily\nleeandheatherwedding\nphotography\nstaff\nviewfindereditors\nviewfinderweb\nwebteam\nworkgroup",
            "ldap_groupfilter_objectclass": "apple-group\nposixGroup",
            "ldap_host": "ldaps:\/\/server.endlesss.co",
            "ldap_login_filter": "(&(|(objectclass=inetOrgPerson))(uid=%uid))",
            "ldap_login_filter_mode": "0",
            "ldap_loginfilter_attributes": "",
            "ldap_loginfilter_email": "0",
            "ldap_loginfilter_username": "1",
            "ldap_nested_groups": "1",
            "ldap_override_main_server": "",
            "ldap_paging_size": "500",
            "ldap_port": "636",
            "ldap_quota_attr": "",
            "ldap_quota_def": "",
            "ldap_tls": "0",
            "ldap_turn_off_cert_check": "0",
            "ldap_turn_on_pwd_change": "0",
            "ldap_user_display_name_2": "",
            "ldap_user_filter_mode": "1",
            "ldap_userfilter_groups": "",
            "ldap_userfilter_objectclass": "inetOrgPerson",
            "ldap_userlist_filter": "(|(objectclass=inetOrgPerson))",
            "s01has_memberof_filter_support": "0",
            "s01home_folder_naming_rule": "",
            "s01last_jpegPhoto_lookup": "0",
            "s01ldap_agent_password": "",
            "s01ldap_attributes_for_group_search": "",
            "s01ldap_attributes_for_user_search": "",
            "s01ldap_backup_host": "",
            "s01ldap_backup_port": "",
            "s01ldap_base": "",
            "s01ldap_base_groups": "",
            "s01ldap_base_users": "",
            "s01ldap_cache_ttl": "600",
            "s01ldap_configuration_active": "0",
            "s01ldap_display_name": "displayName",
            "s01ldap_dn": "",
            "s01ldap_dynamic_group_member_url": "",
            "s01ldap_email_attr": "",
            "s01ldap_experienced_admin": "0",
            "s01ldap_expert_username_attr": "",
            "s01ldap_expert_uuid_group_attr": "",
            "s01ldap_expert_uuid_user_attr": "",
            "s01ldap_group_display_name": "cn",
            "s01ldap_group_filter": "",
            "s01ldap_group_filter_mode": "0",
            "s01ldap_group_member_assoc_attribute": "uniqueMember",
            "s01ldap_groupfilter_groups": "",
            "s01ldap_groupfilter_objectclass": "",
            "s01ldap_host": "",
            "s01ldap_login_filter": "",
            "s01ldap_login_filter_mode": "0",
            "s01ldap_loginfilter_attributes": "",
            "s01ldap_loginfilter_email": "0",
            "s01ldap_loginfilter_username": "1",
            "s01ldap_nested_groups": "0",
            "s01ldap_override_main_server": "",
            "s01ldap_paging_size": "500",
            "s01ldap_port": "",
            "s01ldap_quota_attr": "",
            "s01ldap_quota_def": "",
            "s01ldap_tls": "0",
            "s01ldap_turn_off_cert_check": "0",
            "s01ldap_turn_on_pwd_change": "0",
            "s01ldap_user_display_name_2": "",
            "s01ldap_user_filter_mode": "0",
            "s01ldap_userfilter_groups": "",
            "s01ldap_userfilter_objectclass": "",
            "s01ldap_userlist_filter": "",
            "s01use_memberof_to_detect_membership": "1",
            "types": "authentication",
            "use_memberof_to_detect_membership": "1"
        },
        "user_saml": {
            "general-use_saml_auth_for_desktop": "1",
            "installed_version": "1.3.2",
            "type": "saml",
            "types": "authentication"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "workin2gether": {
            "enabled": "yes",
            "extended": "1",
            "installed_version": "0.9.6",
            "suffix": "rule_displayname",
            "types": ""
        },
        "zenodo": {
            "enabled": "no",
            "installed_version": "0.9.3",
            "types": ""
        }
    }
}

### Client configuration
**Browser:**
Chrome, Safari 

**Operating system:**
macOS High Sierra, Windows 10

**Comment by Schmuuu** [comment] 2018-02-08 09:27
Hi,

Please have a look here:
https://github.com/nextcloud/files_texteditor/issues/39

**Comment by danxuliu** [comment] 2018-02-08 10:12
Yes, this is a duplicate of #39, which was fixed (in master) in #82 and backported to Nextcloud 12 in #84. Therefore I am closing this issue :-)

**Closed by danxuliu** 2018-02-08 10:12 UTC
